// One source for the desktop UI and the flash-resident controller UI.
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, 'web', name), 'utf8');
function bundle() {
  return read('index.html')
    .replace('<link rel="stylesheet" href="styles.css">', () => '<style>' + read('styles.css') + '</style>')
    .replace('<script src="app.js"></script>', () => '<script>window.CONTROLLER_EMBEDDED=true;</script><script>' + read('app.js') + '</script>');
}
function build() {
  const html = bundle();
  if (html.includes(')WEBUI"')) throw new Error('Raw string delimiter collision');
  const header = '// Generated by tools/build-web-ui.js. Edit web/ sources instead.\n#pragma once\nstatic const char kControllerWebHtml[] = R"WEBUI(' + html + ')WEBUI";\n';
  const target = path.join(root, 'firmware/include/WebUi.generated.h');
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(target) || fs.readFileSync(target,'utf8') !== header) throw new Error('Embedded UI is stale; run node tools/build-web-ui.js');
  } else if (!fs.existsSync(target) || fs.readFileSync(target,'utf8') !== header) {
    fs.writeFileSync(target, header);
  }
  console.log('Shared controller UI: ' + Buffer.byteLength(html) + ' bytes');
}
if (require.main === module) build();
module.exports = { bundle };
