#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const {
  exportMariMapperCsv,
  exportPixelblazeArray,
  importMariMapperCsv,
  importPixelblaze,
  normalize,
  validateMapping
} = require("./mapping-utils");

function usage() {
  console.error(`Usage:
  node tools/mapping-convert.js --input <mapping> --output <mapping.json> --id <mapping-id> [--format auto|neutral|pixelblaze|marimapper] [--export neutral|pixelblaze|marimapper] [--fit contain|fill|none] [--dimensions 2|3] [--obj <points.obj>]

Examples:
  node tools/mapping-convert.js --input "Mappings/schrankwand -onlyu.txt" --output config/examples/schrankwand-3d.json --id schrankwand-3d --fit contain --dimensions 3 --obj build/schrankwand-3d.obj
  node tools/mapping-convert.js --format marimapper --input mapping.csv --output config/examples/marimapper.json --id imported-wall --fit none
  node tools/mapping-convert.js --format pixelblaze --input pixelblaze-map.json --export marimapper --output build/pixelblaze-map.csv --id imported-pb
`);
  process.exit(2);
}

function argValue(name) {
  const index = process.argv.indexOf(name);
  if (index === -1) return null;
  return process.argv[index + 1] || null;
}

function parseNeutralMapping(text, id, input) {
  const parsed = JSON.parse(text);
  if (Array.isArray(parsed)) {
    const dimensions = parsed.reduce((max, point) => Math.max(max, point.length), 1);
    return {
      id,
      version: 1,
      pixelCount: parsed.length,
      dimensions,
      fit: "contain",
      source: input,
      points: parsed
    };
  }
  return parsed;
}

function importMapping(text, input, format, id) {
  if (format === "marimapper") return importMariMapperCsv(text, id);
  if (format === "pixelblaze") {
    const result = importPixelblaze(text, id);
    if (result.kind === "generator") {
      throw new Error("Pixelblaze JavaScript generators are preserved but cannot be converted without the Pixelblaze runtime");
    }
    return result.mapping;
  }
  if (format === "neutral") return parseNeutralMapping(text, id, input);

  if (path.extname(input).toLowerCase() === ".csv") return importMariMapperCsv(text, id);
  try {
    const parsed = parseNeutralMapping(text, id, input);
    if (Array.isArray(parsed.points)) return parsed;
  } catch (error) {
    if (!/\.js$/i.test(input)) throw error;
  }
  const result = importPixelblaze(text, id);
  if (result.kind === "generator") {
    throw new Error("Pixelblaze JavaScript generators are preserved but cannot be converted without the Pixelblaze runtime");
  }
  return result.mapping;
}

function applyFitAndDimensions(mapping, fit, dimensions, input) {
  const rawPoints = mapping.points;
  const points = fit === "none" ? rawPoints : normalize(rawPoints, fit);
  const trimmedPoints = points.map(point => point.slice(0, dimensions));
  return {
    ...mapping,
    id: mapping.id || "converted-mapping",
    version: 1,
    pixelCount: trimmedPoints.length,
    dimensions,
    fit,
    source: mapping.source || input,
    points: trimmedPoints
  };
}

function writeObj(points, outputPath) {
  const lines = [
    "# Generated by tools/mapping-convert.js",
    "# Each vertex is one logical LED pixel point.",
    ...points.map(point => {
      const x = point[0] || 0;
      const y = point[1] || 0;
      const z = point[2] || 0;
      return `v ${x} ${y} ${z}`;
    })
  ];
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, `${lines.join("\n")}\n`);
}

function writeOutput(mapping, outputPath, exportFormat) {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  if (exportFormat === "neutral") {
    fs.writeFileSync(outputPath, `${JSON.stringify(mapping, null, 2)}\n`);
  } else if (exportFormat === "pixelblaze") {
    fs.writeFileSync(outputPath, exportPixelblazeArray(mapping, { pretty: true }));
  } else if (exportFormat === "marimapper") {
    fs.writeFileSync(outputPath, exportMariMapperCsv(mapping));
  } else {
    throw new Error(`unknown export format: ${exportFormat}`);
  }
}

function main() {
  const input = argValue("--input");
  const output = argValue("--output");
  const id = argValue("--id") || "converted-mapping";
  const fit = argValue("--fit") || "contain";
  const dimensions = Number(argValue("--dimensions") || 3);
  const format = argValue("--format") || "auto";
  const exportFormat = argValue("--export") || "neutral";
  const obj = argValue("--obj");

  if (!input || !output ||
    !["auto", "neutral", "pixelblaze", "marimapper"].includes(format) ||
    !["neutral", "pixelblaze", "marimapper"].includes(exportFormat) ||
    !["contain", "fill", "none"].includes(fit) ||
    ![2, 3].includes(dimensions)) {
    usage();
  }

  const imported = importMapping(fs.readFileSync(input, "utf8"), input, format, id);
  const mapping = applyFitAndDimensions({ ...imported, id }, fit, dimensions, input);
  const errors = validateMapping(mapping);
  if (errors.length) {
    throw new Error(`generated mapping is invalid:\n${errors.join("\n")}`);
  }

  writeOutput(mapping, output, exportFormat);
  if (obj) writeObj(mapping.points, obj);

  console.log(`Wrote ${mapping.pixelCount} points to ${output} as ${exportFormat}`);
  if (obj) console.log(`Wrote OBJ preview points to ${obj}`);
  if (mapping.compatibility && mapping.compatibility.warnings && mapping.compatibility.warnings.length) {
    mapping.compatibility.warnings.forEach(warning => console.warn(`warning: ${warning}`));
  }
}

main();
